FROM maven:3.8.3-openjdk-17 AS build
COPY . .
RUN mvn clean package -Dskiptests

FROM eclipse-temurin:17-jre-alpine
COPY --from=build /target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
