spring.application.name=expense-tracker-backend
spring.datasource.url=jdbc:postgresql://dpg-d9q9srnqj5pc73c19fcg-a:5432/expense_tracker_db_obxe
spring.datasource.username=expense_tracker_db_obxe_user
spring.datasource.password=OZsYnrz9a1AxwomlGFB4s0Ht01mImANP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


